### PR TITLE
repmgr now merge default config and overrided conf

### LINKED ISSUE #77: repmgr cannot use custom config file => merge configMap and default
**Description**

I'm using the bitnami postgresql-ha helm chart for kubernetes:

I can't use a custom repmgr file 

https://github.com/bitnami/charts/blob/b8d49647ddff31ab0b7c6e6a8fce6c8d4e8ad2df/bitnami/postgresql-ha/values.yaml#L465

I would like to set a manual failover on my cluster or modify the ssh_options parameters.
Actually, If i set a repmgr I need to override the whoe file but how I can use the actual variable replacement ? 

I don't want to hardcode  the name or id or any other parameters because they need to be unique per pod
node_id=$(repmgr_get_node_id)
node_name='${REPMGR_NODE_NAME}'
 [...]

https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/f95d9ef4d93bc73066daef770cb4c3526c641189/11/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L447

**Describe the results you received:**
only the repmgr key I set in my values.yml file are used and the pod crash because the configuration is incorrect

**Describe the results you expected:**
I want a merge with the actual defaults

### PR DESCRIPTION
**Pull request by lerminou**
**Description of the change**

fixes #77 
**Benefits**
some config are specific per pod, now we can merge the configuration with the actual variables from env vars
or we just want to override a specific key but not the whole file

**Possible drawbacks**

**Applicable issues**

**Additional information**

here a bash working version: 
```
#  cat default.txt 
event_notification_command='${REPMGR_EVENTS_DIR}/router.sh %n %e %s "%t" "%d"'
ssh_options='-o "StrictHostKeyChecking no" -v'
use_replication_slots='${REPMGR_USE_REPLICATION_SLOTS}'
pg_bindir='${POSTGRESQL_BIN_DIR}'
# FIXME: these 2 parameter should work
node_id=$(repmgr_get_node_id)
node_name='${REPMGR_NODE_NAME}'
location='${REPMGR_NODE_LOCATION}'
conninfo='user=${REPMGR_USERNAME} $(repmgr_get_conninfo_password) host=${REPMGR_NODE_NETWORK_NAME} dbname=${REPMGR_DATABASE} port=${REPMGR_PORT_NUMBER} connect_timeout=${REPMGR_CONNECT_TIMEOUT}'
failover='automatic'

#  cat custom.txt
ssh_options='" -i ~/.ssh/id_rsa" -v'
use_replication_slots='1'
extra='testing_new_key'

#  grep -v -f default.txt custom.txt | awk -F"=" '{print $1;}' > keys.csv && grep -v -f keys.csv default.txt > final.txt && cat custom.txt >> final.txt

# cat final.txt 
event_notification_command='${REPMGR_EVENTS_DIR}/router.sh %n %e %s "%t" "%d"'
pg_bindir='${POSTGRESQL_BIN_DIR}'
# FIXME: these 2 parameter should work
node_id=$(repmgr_get_node_id)
node_name='${REPMGR_NODE_NAME}'
location='${REPMGR_NODE_LOCATION}'
conninfo='user=${REPMGR_USERNAME} $(repmgr_get_conninfo_password) host=${REPMGR_NODE_NETWORK_NAME} dbname=${REPMGR_DATABASE} port=${REPMGR_PORT_NUMBER} connect_timeout=${REPMGR_CONNECT_TIMEOUT}'
failover='automatic'
ssh_options='" -i ~/.ssh/id_rsa" -v'
use_replication_slots='1'
extra='testing_new_key'

```

### CODE REVIEW

**Comment by alvneiayu** [comment]
hi @lerminou 
Could you include this change in all the versions, please? You are adding it only for the 11 version.

Thanks a lot

Álvaro

File: 11/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh [hunk 1]
```diff
@@ -474,10 +470,17 @@ data_directory='${POSTGRESQL_DATA_DIR}'
...
 pg_ctl_options='-o "--config-file=\"${POSTGRESQL_CONF_FILE}\" --external_pid_file=\"${POSTGRESQL_PID_FILE}\" --hba_file=\"${POSTGRESQL_PGHBA_FILE}\""'
 EOF
+
+    if [[ -f "${REPMGR_MOUNTED_CONF_DIR}/repmgr.conf" ]]; then
+        # remove from default the overrided keys, and append the desired conf
+        grep -v -f "${REPMGR_CONF_FILE}.tmp" "${REPMGR_MOUNTED_CONF_DIR}/repmgr.conf" | awk -F"=" '{print $1;}' > "${REPMGR_CONF_FILE}.keys" && grep -v -f "${REPMGR_CONF_FILE}.keys" "${REPMGR_CONF_FILE}.tmp" > "$REPMGR_CONF_FILE" && cat "${REPMGR_MOUNTED_CONF_DIR}/repmgr.conf" >> "$REPMGR_CONF_FILE"
+    else
+        cp "${REPMGR_CONF_FILE}.tmp" "${REPMGR_CONF_FILE}"
+    fi
         if [[ "$REPMGR_USE_PASSFILE" = "true" ]]; then
```
Comment (alvneiayu) [inline 11/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh:480]: Could you align this one also with the previous if defined, please?

**Review by alvneiayu — CHANGES_REQUESTED** [review]
Please include the change in all the versions and I added another comment in the code.

Thanks a lot for your PR

Álvaro

**Comment by lerminou** [comment]
Hi @alvneiayu i included the change in all versions, and fix the indent.

**Review by alvneiayu — APPROVED** [review]
LGTM
